
name: 'dwh'
version: '1.0.0'

profile: 'dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dbt_date:time_zone: "UTC"

models:
  dwh:
    +persist_docs:
        relation: true
        columns: true
    +on_schema_change: fail
    +config:
      contract:
        enforced: true

    staging:
      +catalog: staging
      meetup:
        +materialized: view
        +schema: staging

    bronze:
      +on_schema_change: append_new_columns
      +catalog: bronze
      meetup:
        +materialized: table
        +schema: meetup

    silver:
      +catalog: silver
      dim:
        +materialized: table
        +schema: dim
      fact:
        +materialized: incremental
        +incremental_strategy: merge
        +schema: fact

    gold:
      +catalog: gold
      meetup:
        +materialized: incremental
        +incremental_strategy: merge
        +schema: meetup
