name: CI

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt dependencies
        run: pip install dbt-databricks

      - name: Create dbt profile
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.dbt
          echo "dwh:" > ~/.dbt/profiles.yml
          echo "  target: ci" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    ci:" >> ~/.dbt/profiles.yml
          echo "      type: databricks" >> ~/.dbt/profiles.yml
          echo "      catalog: meetup" >> ~/.dbt/profiles.yml
          echo "      schema: ci_schema" >> ~/.dbt/profiles.yml
          echo "      host: dbc-10cf7b0c-4f1d.cloud.databricks.com" >> ~/.dbt/profiles.yml
          echo "      http_path: /sql/1.0/warehouses/6268c85844e0cdbe" >> ~/.dbt/profiles.yml
          echo "      threads: 4" >> ~/.dbt/profiles.yml
          echo "      token: '${DATABRICKS_TOKEN}'" >> ~/.dbt/profiles.yml

      - name: Run dbt
        working-directory: dwh
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          dbt deps
          dbt build --target ci --select state:modified+
